#!/usr/bin/env python3
"""
Visualize OOD traces generated by scripts/generate_ood_mini.py.

Features:
- Trajectory plot (stage1/stage2 split)
- Vehicle oriented boxes (length/width/heading)
- Optional map overlay from metric cache token lookup
- Optional GIF animation
"""

from __future__ import annotations

import argparse
import collections
import io
import json
import math
import pickle
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Circle, Polygon as MplPolygon, Rectangle
from PIL import Image

# Make script runnable via absolute path without requiring `pip install -e .`
SCRIPT_PATH = Path(__file__).resolve()
REPO_ROOT = SCRIPT_PATH.parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

try:
    from nuplan.common.actor_state.state_representation import StateSE2
    from nuplan.common.maps.maps_datatypes import SemanticMapLayer
    from nuplan.common.maps.nuplan_map.map_factory import get_maps_api

    from navsim.common.dataloader import MetricCacheLoader

    HAS_MAP_SUPPORT = True
    MAP_IMPORT_ERROR = ""
except Exception as e:  # pragma: no cover - runtime environment dependent
    HAS_MAP_SUPPORT = False
    MAP_IMPORT_ERROR = str(e)


TraceDict = Dict[str, Any]
Point2D = Tuple[float, float]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visualize OOD traces from generated_ood_data.")
    parser.add_argument("--input", type=Path, default=Path("generated_ood_data"), help="Input .json/.pkl file or directory.")
    parser.add_argument("--manifest", type=Path, default=None, help="Optional manifest.jsonl to drive file selection.")
    parser.add_argument(
        "--status-filter",
        type=str,
        default="all",
        choices=["success", "near_miss", "rejected", "all"],
        help="Filter manifest entries by result_status.",
    )
    parser.add_argument("--reason-filter", type=str, default=None, help="Optional reject_reason filter for manifest mode.")
    parser.add_argument("--glob", type=str, default="ood_scene_*.json", help="Glob pattern when --input is a directory.")
    parser.add_argument("--max-files", type=int, default=None, help="Max number of files to visualize.")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory. Defaults to input directory (or file parent).",
    )
    parser.add_argument(
        "--split-index",
        type=int,
        default=None,
        help="Frame index that splits stage1/stage2. Default: infer from num_frames.",
    )
    parser.add_argument("--box-frame", type=str, default="split", help="Frame for static vehicle boxes: start|split|end|<int>.")
    parser.add_argument(
        "--ego-box-frame",
        type=str,
        default="split",
        help="Frame for static ego box: start|split|end|<int>.",
    )
    parser.add_argument(
        "--metric-cache-path",
        type=Path,
        default=None,
        help="Metric cache root to enable map overlay (token -> map lookup).",
    )
    parser.add_argument(
        "--map-root-override",
        type=Path,
        default=None,
        help="Optional local map root override when metric cache stores stale absolute map_root.",
    )
    parser.add_argument("--map-radius", type=float, default=30.0, help="Map query / display radius (meters).")
    parser.add_argument(
        "--map-style",
        type=str,
        default="gis",
        choices=["simple", "gis"],
        help="Map rendering style. 'gis' uses layered semantic colors similar to GIS tooling.",
    )
    parser.add_argument("--hide-route-nodes", action="store_true", help="Hide route start/end node markers.")
    parser.add_argument("--hide-connector-nodes", action="store_true", help="Hide lane/lane-connector node markers.")
    parser.add_argument(
        "--global-frame",
        action="store_true",
        help="Use global coordinates (default: ego-local frame anchored at frame 0).",
    )
    parser.add_argument("--dpi", type=int, default=150, help="PNG resolution.")
    parser.add_argument("--fig-width", type=float, default=12.0, help="Static figure width in inches.")
    parser.add_argument("--fig-height", type=float, default=8.0, help="Static figure height in inches.")
    parser.add_argument("--save-svg", action="store_true", help="Also export static figure as SVG (vector format).")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing outputs.")
    parser.add_argument("--make-gif", action="store_true", help="Also create animated GIF.")
    parser.add_argument("--gif-fps", type=float, default=8.0, help="GIF frame rate when not syncing to timestamps.")
    parser.add_argument("--make-mp4", action="store_true", help="Also create animated MP4.")
    parser.add_argument("--mp4-fps", type=float, default=8.0, help="MP4 frame rate when not syncing to timestamps.")
    parser.add_argument("--mp4-crf", type=int, default=20, help="MP4 quality (lower=better quality, larger file).")
    parser.add_argument("--ffmpeg-bin", type=str, default="ffmpeg", help="ffmpeg executable path.")
    parser.add_argument(
        "--sync-to-timestamps",
        action="store_true",
        help="Play at real-time speed inferred from frame timestamps when available.",
    )
    parser.add_argument(
        "--scene-list-file",
        type=Path,
        default=None,
        help="Optional text file with scene pairs: '<log_name> / <token>' per line.",
    )
    parser.add_argument(
        "--scene-list",
        type=str,
        default=None,
        help="Inline scene-pair text. Supports multiple '<log_name> / <token>' pairs.",
    )
    parser.add_argument(
        "--mini-log-root",
        type=Path,
        default=Path("mini_navsim_logs/mini"),
        help="Directory containing NAVSIM mini log pickle files.",
    )
    parser.add_argument(
        "--history-frames",
        type=int,
        default=10,
        help="History frames before the target token. Use -1 for all frames before token.",
    )
    parser.add_argument(
        "--future-frames",
        type=int,
        default=10,
        help="Future frames after the target token. Use -1 for all frames after token.",
    )
    parser.add_argument("--use-full-log", action="store_true", help="Use full log around token (history=-1,future=-1).")
    parser.add_argument(
        "--traffic-light-frame",
        type=str,
        default="split",
        help="Frame for static traffic-light overlay: start|split|end|<int>.",
    )
    parser.add_argument("--show-tl-hud", action="store_true", help="Show the top-right aggregate TL HUD box.")
    return parser.parse_args()


def list_input_files(input_path: Path, pattern: str, max_files: Optional[int]) -> List[Path]:
    if input_path.is_file():
        return [input_path]
    if not input_path.exists():
        raise FileNotFoundError(f"Input does not exist: {input_path}")
    files = sorted(input_path.glob(pattern))
    if not files and pattern.endswith(".json"):
        files = sorted(input_path.glob(pattern.replace(".json", ".pkl")))
    if max_files is not None:
        files = files[:max_files]
    return files


def list_files_from_manifest(
    manifest_path: Path,
    status_filter: str,
    reason_filter: Optional[str],
    max_files: Optional[int],
) -> Tuple[List[Path], Dict[str, Dict[str, Any]]]:
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest does not exist: {manifest_path}")
    files: List[Path] = []
    meta_by_file: Dict[str, Dict[str, Any]] = {}
    seen: set[str] = set()
    with manifest_path.open("r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line:
                continue
            entry = json.loads(line)
            status = str(entry.get("result_status", "success"))
            if status_filter != "all" and status != status_filter:
                continue
            if reason_filter is not None and str(entry.get("reject_reason")) != reason_filter:
                continue
            file_candidate = entry.get("json_path") or entry.get("pkl_path")
            if not file_candidate:
                continue
            p = Path(str(file_candidate)).expanduser()
            if not p.exists():
                continue
            key = str(p.resolve())
            if key in seen:
                continue
            seen.add(key)
            files.append(p)
            meta_by_file[key] = entry
            if max_files is not None and len(files) >= max_files:
                break
    return files, meta_by_file


SCENE_PAIR_PATTERN = re.compile(r"([^\s/]+)\s*/\s*([0-9a-fA-F]{16})")


def parse_scene_pairs_text(text: str) -> List[Tuple[str, str]]:
    pairs: List[Tuple[str, str]] = []
    seen: set[Tuple[str, str]] = set()
    for match in SCENE_PAIR_PATTERN.finditer(text):
        log_name = str(match.group(1)).strip()
        token = str(match.group(2)).strip().lower()
        pair = (log_name, token)
        if pair in seen:
            continue
        seen.add(pair)
        pairs.append(pair)
    return pairs


def collect_scene_pairs(scene_list_file: Optional[Path], inline_scene_list: Optional[str]) -> List[Tuple[str, str]]:
    chunks: List[str] = []
    if scene_list_file is not None:
        if not scene_list_file.exists():
            raise FileNotFoundError(f"scene list file does not exist: {scene_list_file}")
        chunks.append(scene_list_file.read_text(encoding="utf-8"))
    if inline_scene_list:
        chunks.append(inline_scene_list)
    if not chunks:
        return []
    return parse_scene_pairs_text("\n".join(chunks))


def load_trace(path: Path) -> TraceDict:
    suffix = path.suffix.lower()
    if suffix == ".json":
        return json.loads(path.read_text(encoding="utf-8"))
    if suffix == ".pkl":
        with path.open("rb") as f:
            return pickle.load(f)
    raise ValueError(f"Unsupported file format: {path}")


def validate_trace(trace: TraceDict, path: Path) -> None:
    required_keys = {"token", "num_frames", "frames", "stage1_score"}
    missing = required_keys - set(trace.keys())
    if missing:
        raise ValueError(f"{path}: missing keys {sorted(missing)}")
    if not isinstance(trace["frames"], list) or len(trace["frames"]) == 0:
        raise ValueError(f"{path}: frames must be a non-empty list")


def infer_split_index(num_frames: int) -> int:
    if num_frames <= 1:
        return 0
    if num_frames % 2 == 1:
        return (num_frames - 1) // 2
    return num_frames // 2


def infer_split_index_from_trace(trace: TraceDict) -> int:
    n = int(trace.get("num_frames", 0))
    if n <= 1:
        return 0
    strong = trace.get("strong_longtail", {})
    longtail = trace.get("longtail", {})
    for bucket in (strong, longtail):
        if isinstance(bucket, dict) and "split_idx" in bucket:
            try:
                return max(0, min(int(round(float(bucket["split_idx"]))), n - 1))
            except Exception:
                pass
    stage2 = trace.get("stage2_score")
    if not isinstance(stage2, dict) or not stage2:
        return n - 1
    return infer_split_index(n)


def parse_box_frame(value: str, split_idx: int, num_frames: int) -> int:
    if value == "start":
        return 0
    if value == "split":
        return split_idx
    if value == "end":
        return num_frames - 1
    idx = int(value)
    return max(0, min(idx, num_frames - 1))


def yaw_from_transform_matrix(ego2global: np.ndarray) -> float:
    return float(math.atan2(float(ego2global[1, 0]), float(ego2global[0, 0])))


def transform_local_xy_to_global(ego2global: np.ndarray, x_local: float, y_local: float) -> Tuple[float, float]:
    point_local = np.array([x_local, y_local, 0.0, 1.0], dtype=np.float64)
    point_global = ego2global @ point_local
    return float(point_global[0]), float(point_global[1])


def build_trace_from_scene_pair(
    log_frames: List[Dict[str, Any]],
    log_name: str,
    token: str,
    history_frames: int,
    future_frames: int,
) -> Optional[TraceDict]:
    token_to_index = {str(frame.get("token")): idx for idx, frame in enumerate(log_frames)}
    if token not in token_to_index:
        return None

    center_idx = token_to_index[token]
    start_idx = 0 if history_frames < 0 else max(0, center_idx - max(0, history_frames))
    end_idx = (len(log_frames) - 1) if future_frames < 0 else min(len(log_frames) - 1, center_idx + max(0, future_frames))
    scene_frames = log_frames[start_idx : end_idx + 1]
    split_idx = center_idx - start_idx

    trace_frames: List[Dict[str, Any]] = []
    for frame in scene_frames:
        ego2global = np.asarray(frame["ego2global"], dtype=np.float64)
        ego_x = float(frame["ego2global_translation"][0])
        ego_y = float(frame["ego2global_translation"][1])
        ego_heading = yaw_from_transform_matrix(ego2global)
        ego_vx, ego_vy = float(frame["ego_dynamic_state"][0]), float(frame["ego_dynamic_state"][1])
        ego_speed = float(math.hypot(ego_vx, ego_vy))

        boxes = frame["anns"]["gt_boxes"]
        names = frame["anns"]["gt_names"]
        vehicles: List[Dict[str, Any]] = []
        for box, name in zip(boxes, names):
            # Keep vehicle-class boxes only for readability.
            if str(name) != "vehicle":
                continue
            x_local, y_local = float(box[0]), float(box[1])
            length, width = float(box[3]), float(box[4])
            heading_local = float(box[6])
            vx_global, vy_global = transform_local_xy_to_global(ego2global, x_local, y_local)
            vehicles.append(
                {
                    "x": vx_global,
                    "y": vy_global,
                    "heading": normalize_angle(ego_heading + heading_local),
                    "width": width,
                    "length": length,
                }
            )

        traffic_lights = [[str(lane_connector_id), bool(is_red)] for lane_connector_id, is_red in frame["traffic_lights"]]
        trace_frames.append(
            {
                "token": str(frame["token"]),
                "timestamp": int(frame.get("timestamp", 0)),
                "ego": {
                    "x": ego_x,
                    "y": ego_y,
                    "heading": ego_heading,
                    "velocity": ego_speed,
                },
                "vehicles": vehicles,
                "traffic_lights": traffic_lights,
            }
        )

    return {
        "token": token,
        "log_name": log_name,
        "num_frames": len(trace_frames),
        "frames": trace_frames,
        "stage1_score": {},
        "stage2_score": {},
        "strong_longtail": {"split_idx": split_idx},
    }


def build_diagnostic_lines(trace: TraceDict, manifest_meta: Optional[Dict[str, Any]]) -> List[str]:
    def _sf(v: Any) -> float:
        try:
            return float(v)
        except Exception:
            return float("nan")

    lines: List[str] = []
    merged: Dict[str, Any] = {}
    if isinstance(manifest_meta, dict):
        merged.update(manifest_meta)
    merged.update(trace)

    status = merged.get("result_status")
    reason = merged.get("reject_reason")
    stage = merged.get("search_stage")
    if status is not None or reason is not None or stage is not None:
        lines.append(f"status={status}, reason={reason}, stage={stage}")

    strong = merged.get("strong_longtail")
    if isinstance(strong, dict):
        lines.append(
            "strong: "
            f"score={_sf(strong.get('strong_longtail_score')):.3f}, "
            f"d1={_sf(strong.get('stage1_min_dist_m')):.2f}m, "
            f"d2={_sf(strong.get('stage2_min_dist_m')):.2f}m, "
            f"disp2={_sf(strong.get('stage2_displacement_m')):.2f}m"
        )

    lt = merged.get("longtail")
    if isinstance(lt, dict):
        lines.append(
            "ranked: "
            f"score={_sf(lt.get('longtail_score')):.3f}, "
            f"risk={_sf(lt.get('risk_score')):.3f}, "
            f"recovery={_sf(lt.get('recovery_score')):.3f}, "
            f"cont={_sf(lt.get('continuity_score')):.3f}"
        )
    return lines


def normalize_angle(angle: float) -> float:
    return (angle + math.pi) % (2 * math.pi) - math.pi


def to_local(points: Sequence[Point2D], origin: Point2D, heading: float) -> List[Point2D]:
    ox, oy = origin
    c = math.cos(heading)
    s = math.sin(heading)
    out: List[Point2D] = []
    for x, y in points:
        dx, dy = x - ox, y - oy
        lx = c * dx + s * dy
        ly = -s * dx + c * dy
        out.append((lx, ly))
    return out


def trace_to_series(
    trace: TraceDict,
    use_global_frame: bool,
) -> Tuple[List[Point2D], List[float], List[List[Dict[str, Any]]], List[List[Point2D]]]:
    frames = trace["frames"]
    ego_points_global = [(float(f["ego"]["x"]), float(f["ego"]["y"])) for f in frames]
    ego_speed = [float(f["ego"]["velocity"]) for f in frames]
    all_vehicles = [f.get("vehicles", []) for f in frames]

    if use_global_frame:
        ego_points = ego_points_global
        vehicles_points = [[(float(v["x"]), float(v["y"])) for v in vehicles] for vehicles in all_vehicles]
        return ego_points, ego_speed, all_vehicles, vehicles_points

    init_heading = float(frames[0]["ego"]["heading"])
    origin = ego_points_global[0]
    ego_points = to_local(ego_points_global, origin, init_heading)
    vehicles_points = []
    for vehicles in all_vehicles:
        pts = [(float(v["x"]), float(v["y"])) for v in vehicles]
        vehicles_points.append(to_local(pts, origin, init_heading))
    return ego_points, ego_speed, all_vehicles, vehicles_points


def nearest_vehicle_distance(ego_points: Sequence[Point2D], vehicles_points: Sequence[Sequence[Point2D]]) -> List[float]:
    dist_list: List[float] = []
    for ego, vehicles in zip(ego_points, vehicles_points):
        ex, ey = ego
        if not vehicles:
            dist_list.append(float("nan"))
            continue
        dmin = min(math.hypot(vx - ex, vy - ey) for vx, vy in vehicles)
        dist_list.append(dmin)
    return dist_list


def score_text(score: Dict[str, float]) -> str:
    return (
        f"pdm={score.get('pdm_score', float('nan')):.3f}, "
        f"NC={score.get('no_at_fault_collisions', float('nan')):.2f}, "
        f"DAC={score.get('drivable_area_compliance', float('nan')):.2f}, "
        f"DDC={score.get('driving_direction_compliance', float('nan')):.2f}, "
        f"TLC={score.get('traffic_light_compliance', float('nan')):.2f}, "
        f"EP={score.get('ego_progress', float('nan')):.2f}"
    )


def oriented_box_corners(center_x: float, center_y: float, heading: float, length: float, width: float) -> List[Point2D]:
    half_l = 0.5 * length
    half_w = 0.5 * width
    local = [(half_l, half_w), (half_l, -half_w), (-half_l, -half_w), (-half_l, half_w)]
    c = math.cos(heading)
    s = math.sin(heading)
    return [
        (center_x + c * dx - s * dy, center_y + s * dx + c * dy)
        for dx, dy in local
    ]


def ego_box_payload(frame: Dict[str, Any]) -> Dict[str, float]:
    ego = frame["ego"]
    return {
        "x": float(ego["x"]),
        "y": float(ego["y"]),
        "heading": float(ego.get("heading", 0.0)),
        # Fallback dimensions if ego size is not serialized in trace.
        "width": float(ego.get("width", 2.0)),
        "length": float(ego.get("length", 4.8)),
    }


def draw_vehicle_boxes(
    ax: plt.Axes,
    vehicles: Sequence[Dict[str, Any]],
    use_global_frame: bool,
    origin_global: Point2D,
    origin_heading: float,
    color: str = "#355C7D",
    fill_alpha: float = 0.12,
    line_alpha: float = 0.9,
    line_width: float = 1.0,
    label: Optional[str] = None,
    zorder_base: float = 12.0,
) -> None:
    label_used = False
    for v in vehicles:
        cx = float(v["x"])
        cy = float(v["y"])
        heading = float(v.get("heading", 0.0))
        width = float(v.get("width", 1.8))
        length = float(v.get("length", 4.5))
        if not use_global_frame:
            cx, cy = to_local([(cx, cy)], origin_global, origin_heading)[0]
            heading = normalize_angle(heading - origin_heading)
        corners = oriented_box_corners(cx, cy, heading, length, width)
        patch = MplPolygon(
            corners,
            closed=True,
            facecolor=color,
            edgecolor=color,
            linewidth=line_width,
            alpha=fill_alpha,
            zorder=zorder_base,
            label=(label if (label and not label_used) else None),
        )
        ax.add_patch(patch)
        ax.plot(
            [p[0] for p in corners] + [corners[0][0]],
            [p[1] for p in corners] + [corners[0][1]],
            color=color,
            lw=line_width,
            alpha=line_alpha,
            zorder=zorder_base + 0.1,
        )
        label_used = True


def _iter_polygon_exteriors(geometry: Any) -> List[List[Point2D]]:
    if geometry is None:
        return []
    if hasattr(geometry, "geoms"):
        out: List[List[Point2D]] = []
        for g in geometry.geoms:
            out.extend(_iter_polygon_exteriors(g))
        return out
    if not hasattr(geometry, "exterior"):
        return []
    coords = [(float(x), float(y)) for x, y, *_ in geometry.exterior.coords]
    return [coords]


def _iter_lines(geometry: Any) -> List[List[Point2D]]:
    if geometry is None:
        return []
    if hasattr(geometry, "geoms"):
        out: List[List[Point2D]] = []
        for g in geometry.geoms:
            out.extend(_iter_lines(g))
        return out
    if not hasattr(geometry, "coords"):
        return []
    coords = [(float(x), float(y)) for x, y, *_ in geometry.coords]
    return [coords]


def _to_plot_coords(points: List[Point2D], use_global_frame: bool, origin: Point2D, heading: float) -> List[Point2D]:
    if use_global_frame:
        return points
    return to_local(points, origin, heading)


def prepare_map_layers(
    metric_cache_loader: Optional[Any],
    map_api_cache: Dict[Tuple[str, str, str], Any],
    trace: TraceDict,
    use_global_frame: bool,
    map_radius: float,
    map_root_override: Optional[Path],
) -> Optional[Dict[str, Any]]:
    if metric_cache_loader is None:
        return None

    token = str(trace["token"])
    try:
        metric_cache = metric_cache_loader.get_from_token(token)
    except Exception:
        return None

    params = metric_cache.map_parameters
    map_root = str(map_root_override.resolve()) if map_root_override is not None else str(params.map_root)
    key = (map_root, str(params.map_version), str(params.map_name))
    try:
        if key not in map_api_cache:
            map_api_cache[key] = get_maps_api(*key)
        map_api = map_api_cache[key]
    except Exception:
        return None

    first = trace["frames"][0]["ego"]
    origin_global = (float(first["x"]), float(first["y"]))
    origin_heading = float(first["heading"])
    origin_state = StateSE2(origin_global[0], origin_global[1], origin_heading)

    polygon_layer_specs: List[Tuple[str, Any]] = [
        ("lane", SemanticMapLayer.LANE),
        ("lane_connector", SemanticMapLayer.LANE_CONNECTOR),
        ("intersection", SemanticMapLayer.INTERSECTION),
        ("crosswalk", SemanticMapLayer.CROSSWALK),
        ("stop_line", SemanticMapLayer.STOP_LINE),
        ("walkway", SemanticMapLayer.WALKWAYS),
        ("carpark", SemanticMapLayer.CARPARK_AREA),
    ]
    polyline_layer_specs: List[Tuple[str, Any]] = [
        ("lane_baseline", SemanticMapLayer.LANE),
        ("lane_connector_baseline", SemanticMapLayer.LANE_CONNECTOR),
    ]
    requested_layers = list({layer for _, layer in polygon_layer_specs + polyline_layer_specs})
    map_object_dict = map_api.get_proximal_map_objects(
        point=origin_state.point,
        radius=map_radius,
        layers=requested_layers,
    )

    polygons_by_layer: Dict[str, List[List[Point2D]]] = {name: [] for name, _ in polygon_layer_specs}
    lines_by_layer: Dict[str, List[List[Point2D]]] = {name: [] for name, _ in polyline_layer_specs}
    route_lines: List[List[Point2D]] = []

    for layer_name, layer in polygon_layer_specs:
        for map_object in map_object_dict.get(layer, []):
            for poly in _iter_polygon_exteriors(getattr(map_object, "polygon", None)):
                polygons_by_layer[layer_name].append(_to_plot_coords(poly, use_global_frame, origin_global, origin_heading))

    for layer_name, layer in polyline_layer_specs:
        for map_object in map_object_dict.get(layer, []):
            base = getattr(getattr(map_object, "baseline_path", None), "linestring", None)
            for line in _iter_lines(base):
                lines_by_layer[layer_name].append(_to_plot_coords(line, use_global_frame, origin_global, origin_heading))

    for lane_id in metric_cache.route_lane_ids:
        lane = map_api.get_map_object(lane_id, SemanticMapLayer.LANE)
        if lane is None:
            lane = map_api.get_map_object(lane_id, SemanticMapLayer.LANE_CONNECTOR)
        if lane is None:
            continue
        base = getattr(getattr(lane, "baseline_path", None), "linestring", None)
        for line in _iter_lines(base):
            route_lines.append(_to_plot_coords(line, use_global_frame, origin_global, origin_heading))

    def _dedup_nodes(nodes: List[Point2D], precision: int = 2) -> List[Point2D]:
        seen: set[Tuple[float, float]] = set()
        out: List[Point2D] = []
        for x, y in nodes:
            key = (round(float(x), precision), round(float(y), precision))
            if key in seen:
                continue
            seen.add(key)
            out.append((float(x), float(y)))
        return out

    route_nodes_raw: List[Point2D] = []
    for line in route_lines:
        if len(line) >= 2:
            route_nodes_raw.append(line[0])
            route_nodes_raw.append(line[-1])
    route_nodes = _dedup_nodes(route_nodes_raw, precision=2)

    connector_nodes_raw: List[Point2D] = []
    for key in ("lane_baseline", "lane_connector_baseline"):
        for line in lines_by_layer.get(key, []):
            if len(line) >= 2:
                connector_nodes_raw.append(line[0])
                connector_nodes_raw.append(line[-1])
    connector_nodes = _dedup_nodes(connector_nodes_raw, precision=2)

    traffic_lights_by_frame: List[Dict[str, List[List[Point2D]]]] = []
    for frame in trace.get("frames", []):
        traffic_light_entries = frame.get("traffic_lights", [])
        red_polygons: List[List[Point2D]] = []
        green_polygons: List[List[Point2D]] = []
        if isinstance(traffic_light_entries, list):
            for entry in traffic_light_entries:
                if not isinstance(entry, (list, tuple)) or len(entry) != 2:
                    continue
                lane_connector_id = str(entry[0])
                is_red = bool(entry[1])
                lane_connector = map_api.get_map_object(lane_connector_id, SemanticMapLayer.LANE_CONNECTOR)
                if lane_connector is None:
                    continue
                for poly in _iter_polygon_exteriors(getattr(lane_connector, "polygon", None)):
                    poly_plot = _to_plot_coords(poly, use_global_frame, origin_global, origin_heading)
                    if is_red:
                        red_polygons.append(poly_plot)
                    else:
                        green_polygons.append(poly_plot)
        traffic_lights_by_frame.append({"red": red_polygons, "green": green_polygons})

    # Build TL anchor points on stop lines per controlled lane-connector:
    # traffic_light -> lane_connector -> stop_line center(s)
    tl_lane_ids: set[str] = set()
    for frame in trace.get("frames", []):
        entries = frame.get("traffic_lights", [])
        if not isinstance(entries, list):
            continue
        for entry in entries:
            if isinstance(entry, (list, tuple)) and len(entry) >= 1:
                tl_lane_ids.add(str(entry[0]))

    tl_anchors_by_lane_connector: Dict[str, List[Point2D]] = {}
    for lane_connector_id in sorted(tl_lane_ids):
        lane_connector = map_api.get_map_object(lane_connector_id, SemanticMapLayer.LANE_CONNECTOR)
        if lane_connector is None:
            continue

        anchors: List[Point2D] = []
        stop_lines = getattr(lane_connector, "stop_lines", None) or []
        for stop_line in stop_lines:
            poly = getattr(stop_line, "polygon", None)
            if poly is None:
                continue
            centroid = poly.centroid
            anchors.append(
                _to_plot_coords(
                    [(float(centroid.x), float(centroid.y))],
                    use_global_frame,
                    origin_global,
                    origin_heading,
                )[0]
            )
        if not anchors:
            # Fallback: use lane-connector polygon centroid if stop line unavailable.
            lc_poly = getattr(lane_connector, "polygon", None)
            if lc_poly is not None:
                c = lc_poly.centroid
                anchors.append(
                    _to_plot_coords(
                        [(float(c.x), float(c.y))],
                        use_global_frame,
                        origin_global,
                        origin_heading,
                    )[0]
                )
        if anchors:
            tl_anchors_by_lane_connector[lane_connector_id] = anchors

    return {
        "polygons_by_layer": polygons_by_layer,
        "lines_by_layer": lines_by_layer,
        "route_lines": route_lines,
        "route_nodes": route_nodes,
        "connector_nodes": connector_nodes,
        "traffic_lights_by_frame": traffic_lights_by_frame,
        "tl_anchors_by_lane_connector": tl_anchors_by_lane_connector,
        "route_lane_ids_set": {str(lane_id) for lane_id in metric_cache.route_lane_ids},
        "origin_global": [origin_global[0], origin_global[1]],
    }


def draw_map_layers(
    ax: plt.Axes,
    map_layers: Optional[Dict[str, Any]],
    map_style: str = "gis",
    show_route_nodes: bool = True,
    show_connector_nodes: bool = True,
) -> None:
    if not map_layers:
        return

    polygons_by_layer = map_layers.get("polygons_by_layer", {})
    lines_by_layer = map_layers.get("lines_by_layer", {})

    if map_style == "simple":
        for polys in polygons_by_layer.values():
            for poly in polys:
                if len(poly) < 3:
                    continue
                ax.fill(
                    [p[0] for p in poly],
                    [p[1] for p in poly],
                    color="#ECEFF4",
                    alpha=0.55,
                    zorder=0,
                    linewidth=0,
                )
                ax.plot([p[0] for p in poly], [p[1] for p in poly], color="#CAD2DC", lw=0.6, alpha=0.7, zorder=1)
        for lines in lines_by_layer.values():
            for line in lines:
                if len(line) < 2:
                    continue
                ax.plot([p[0] for p in line], [p[1] for p in line], color="#AAB4C3", lw=0.7, alpha=0.75, zorder=2)
    else:
        # GIS-like semantic styling for clearer region separation.
        poly_styles: Dict[str, Dict[str, Any]] = {
            "drivable_area": {"fc": "#D7DEE8", "ec": "#BCC6D3", "alpha": 0.18, "lw": 0.5, "hatch": None, "z": 0},
            "lane": {"fc": "#F7DCCB", "ec": "#E5B79D", "alpha": 0.55, "lw": 0.55, "hatch": "//", "z": 1},
            "lane_connector": {"fc": "#CFEFD8", "ec": "#88C79B", "alpha": 0.42, "lw": 0.65, "hatch": None, "z": 2},
            "intersection": {"fc": "#BDE8C7", "ec": "#7FBA91", "alpha": 0.36, "lw": 0.65, "hatch": None, "z": 3},
            "crosswalk": {"fc": "#C8B8F2", "ec": "#9B88D1", "alpha": 0.35, "lw": 0.65, "hatch": None, "z": 4},
            "stop_line": {"fc": "#F4B8B8", "ec": "#CC7A7A", "alpha": 0.62, "lw": 0.75, "hatch": None, "z": 5},
            "walkway": {"fc": "#DEE4EA", "ec": "#B9C4CF", "alpha": 0.25, "lw": 0.5, "hatch": None, "z": 0},
            "carpark": {"fc": "#DBF0F3", "ec": "#A5CCD3", "alpha": 0.22, "lw": 0.5, "hatch": None, "z": 0},
        }
        for layer_name, style in poly_styles.items():
            for poly in polygons_by_layer.get(layer_name, []):
                if len(poly) < 3:
                    continue
                ax.fill(
                    [p[0] for p in poly],
                    [p[1] for p in poly],
                    facecolor=style["fc"],
                    edgecolor=style["ec"],
                    alpha=style["alpha"],
                    linewidth=style["lw"],
                    hatch=style["hatch"],
                    zorder=style["z"],
                )

        for line in lines_by_layer.get("lane_baseline", []):
            if len(line) < 2:
                continue
            ax.plot([p[0] for p in line], [p[1] for p in line], color="#2A8A53", lw=0.9, alpha=0.72, zorder=6)
        for line in lines_by_layer.get("lane_connector_baseline", []):
            if len(line) < 2:
                continue
            ax.plot([p[0] for p in line], [p[1] for p in line], color="#2F9E5D", lw=0.85, alpha=0.7, zorder=6)

    for line in map_layers.get("route_lines", []):
        if len(line) < 2:
            continue
        ax.plot([p[0] for p in line], [p[1] for p in line], color="#C62828", lw=1.15, alpha=0.85, zorder=7)

    if show_connector_nodes:
        nodes = map_layers.get("connector_nodes", [])
        if nodes:
            ax.scatter(
                [p[0] for p in nodes],
                [p[1] for p in nodes],
                s=10,
                c="#3B2C56",
                alpha=0.75,
                linewidths=0.25,
                edgecolors="#E8DEF8",
                zorder=8,
            )
    if show_route_nodes:
        nodes = map_layers.get("route_nodes", [])
        if nodes:
            ax.scatter(
                [p[0] for p in nodes],
                [p[1] for p in nodes],
                s=14,
                c="#1B5E20",
                alpha=0.92,
                linewidths=0.35,
                edgecolors="#111111",
                zorder=9,
            )


def _normalize_light_state(raw_state: Any) -> str:
    if isinstance(raw_state, bool):
        return "RED" if raw_state else "GREEN"
    if isinstance(raw_state, (int, float)):
        if int(raw_state) == 2:
            return "YELLOW"
        return "RED" if int(raw_state) == 1 else "GREEN"
    if isinstance(raw_state, str):
        s = raw_state.strip().lower()
        if s in ("red", "r", "stop"):
            return "RED"
        if s in ("green", "g", "go"):
            return "GREEN"
        if s in ("yellow", "amber", "y"):
            return "YELLOW"
    if isinstance(raw_state, dict):
        return _normalize_light_state(raw_state.get("state", raw_state.get("color", "yellow")))
    return "YELLOW"


def _light_state_color(state: str) -> str:
    if state == "RED":
        return "#E53935"
    if state == "GREEN":
        return "#43A047"
    return "#FBC02D"


def draw_traffic_lights(
    ax: plt.Axes,
    trace: TraceDict,
    map_layers: Optional[Dict[str, Any]],
    frame_idx: int,
    marker_radius_m: float = 0.45,
) -> None:
    if not map_layers:
        return
    frames = trace.get("frames", [])
    if not isinstance(frames, list) or not frames:
        return
    idx = max(0, min(frame_idx, len(frames) - 1))

    route_lane_ids_set = map_layers.get("route_lane_ids_set")
    entries = _frame_traffic_light_entries(frames[idx], route_lane_ids_set)
    if not entries:
        return

    anchors_by_lane = map_layers.get("tl_anchors_by_lane_connector", {})
    markers: List[List[Any]] = []  # [x, y, state, lane_id]
    for lane_id, state in entries:
        anchors = anchors_by_lane.get(lane_id, [])
        for anchor in anchors:
            markers.append([float(anchor[0]), float(anchor[1]), state, lane_id])

    if not markers:
        return

    # If multiple movements share one stop line center, spread markers in a tiny ring.
    grouped: Dict[Tuple[float, float], List[int]] = collections.defaultdict(list)
    for i, (x, y, _, _) in enumerate(markers):
        grouped[(round(x, 2), round(y, 2))].append(i)
    for group_indices in grouped.values():
        n = len(group_indices)
        if n <= 1:
            continue
        spread_r = 0.55
        for j, marker_idx in enumerate(group_indices):
            theta = 2.0 * math.pi * float(j) / float(n)
            markers[marker_idx][0] += spread_r * math.cos(theta)
            markers[marker_idx][1] += spread_r * math.sin(theta)

    for x, y, state, _ in markers:
        ax.add_patch(
            Circle(
                (x, y),
                radius=marker_radius_m,
                facecolor=_light_state_color(state),
                edgecolor="#111111",
                linewidth=0.55,
                alpha=0.95,
                zorder=10,
            )
        )


def _frame_traffic_light_entries(
    frame: Dict[str, Any],
    route_lane_ids_set: Optional[set[str]],
) -> List[Tuple[str, str]]:
    entries_raw = frame.get("traffic_lights", [])
    entries: List[Tuple[str, str]] = []
    if not isinstance(entries_raw, list):
        return entries
    for item in entries_raw:
        if not isinstance(item, (list, tuple)) or len(item) != 2:
            continue
        lane_id = str(item[0])
        state = _normalize_light_state(item[1])
        entries.append((lane_id, state))
    if route_lane_ids_set:
        filtered = [entry for entry in entries if entry[0] in route_lane_ids_set]
        if filtered:
            return filtered
    return entries


def _summarize_light_state(entries: List[Tuple[str, str]]) -> Tuple[str, int, int, int]:
    if not entries:
        return "N/A", 0, 0, 0
    red_count = sum(1 for _, state in entries if state == "RED")
    yellow_count = sum(1 for _, state in entries if state == "YELLOW")
    green_count = sum(1 for _, state in entries if state == "GREEN")
    if red_count > 0 and green_count == 0:
        return "RED", red_count, yellow_count, green_count
    if green_count > 0 and red_count == 0:
        return "GREEN", red_count, yellow_count, green_count
    if yellow_count > 0 and red_count == 0 and green_count == 0:
        return "YELLOW", red_count, yellow_count, green_count
    return "MIXED", red_count, yellow_count, green_count


def _estimate_countdown_seconds(
    trace: TraceDict,
    frame_idx: int,
    route_lane_ids_set: Optional[set[str]],
) -> Optional[float]:
    frames = trace.get("frames", [])
    if not isinstance(frames, list) or frame_idx >= len(frames):
        return None

    curr_entries = _frame_traffic_light_entries(frames[frame_idx], route_lane_ids_set)
    curr_state, _, _, _ = _summarize_light_state(curr_entries)
    if curr_state == "N/A":
        return None

    curr_ts = frames[frame_idx].get("timestamp")
    if curr_ts is None:
        return None

    for j in range(frame_idx + 1, len(frames)):
        next_entries = _frame_traffic_light_entries(frames[j], route_lane_ids_set)
        next_state, _, _, _ = _summarize_light_state(next_entries)
        if next_state == "N/A":
            continue
        if next_state != curr_state:
            next_ts = frames[j].get("timestamp")
            if next_ts is None:
                return None
            return max(0.0, (float(next_ts) - float(curr_ts)) / 1e6)
    return None


def infer_realtime_fps_from_trace(trace: TraceDict) -> Optional[float]:
    frames = trace.get("frames", [])
    if not isinstance(frames, list) or len(frames) < 2:
        return None
    timestamps: List[float] = []
    for frame in frames:
        ts = frame.get("timestamp")
        if ts is None:
            continue
        try:
            timestamps.append(float(ts))
        except Exception:
            continue
    if len(timestamps) < 2:
        return None
    deltas_s = []
    for i in range(len(timestamps) - 1):
        dt = (timestamps[i + 1] - timestamps[i]) / 1e6
        if dt > 1e-6:
            deltas_s.append(dt)
    if not deltas_s:
        return None
    median_dt = float(np.median(np.asarray(deltas_s, dtype=np.float64)))
    if median_dt <= 1e-6:
        return None
    return 1.0 / median_dt


def draw_traffic_light_hud(
    ax: plt.Axes,
    trace: TraceDict,
    frame_idx: int,
    map_layers: Optional[Dict[str, Any]],
) -> None:
    frames = trace.get("frames", [])
    if not isinstance(frames, list) or not frames:
        return
    idx = max(0, min(frame_idx, len(frames) - 1))
    route_lane_ids_set = None
    if map_layers is not None:
        route_lane_ids_set = map_layers.get("route_lane_ids_set")

    entries = _frame_traffic_light_entries(frames[idx], route_lane_ids_set)
    state, red_count, yellow_count, green_count = _summarize_light_state(entries)
    if state == "N/A":
        return

    countdown_s = _estimate_countdown_seconds(trace, idx, route_lane_ids_set)
    if countdown_s is None:
        countdown_text = "--"
    else:
        countdown_text = f"{countdown_s:.1f}s"

    if state == "RED":
        color = "#D32F2F"
    elif state == "GREEN":
        color = "#2E7D32"
    elif state == "YELLOW":
        color = "#F9A825"
    else:
        color = "#F9A825"

    # Right-top traffic light HUD with light color + countdown.
    box_w, box_h = 0.24, 0.14
    box_x = 1.0 - box_w - 0.015
    box_y = 1.0 - box_h - 0.02
    rect = Rectangle(
        (box_x, box_y),
        box_w,
        box_h,
        transform=ax.transAxes,
        facecolor="white",
        edgecolor="#555555",
        linewidth=0.8,
        alpha=0.9,
        zorder=20,
    )
    ax.add_patch(rect)
    light = Circle(
        (box_x + 0.035, box_y + box_h - 0.04),
        0.015,
        transform=ax.transAxes,
        facecolor=color,
        edgecolor="#333333",
        linewidth=0.6,
        zorder=21,
    )
    ax.add_patch(light)
    ax.text(
        box_x + 0.06,
        box_y + box_h - 0.04,
        f"TL {state}",
        transform=ax.transAxes,
        fontsize=8,
        ha="left",
        va="center",
        color="#1A1A1A",
        zorder=21,
    )
    ax.text(
        box_x + 0.02,
        box_y + 0.05,
        f"Countdown: {countdown_text}",
        transform=ax.transAxes,
        fontsize=8,
        ha="left",
        va="center",
        color="#1A1A1A",
        zorder=21,
    )
    ax.text(
        box_x + 0.02,
        box_y + 0.02,
        f"R={red_count} Y={yellow_count} G={green_count}",
        transform=ax.transAxes,
        fontsize=7,
        ha="left",
        va="center",
        color="#555555",
        zorder=21,
    )


def apply_bev_limits(
    ax: plt.Axes,
    ego_points: List[Point2D],
    extra_points: Optional[List[Point2D]],
    map_layers: Optional[Dict[str, Any]],
    map_radius: float,
    use_global_frame: bool,
) -> None:
    if map_layers is not None:
        if use_global_frame:
            ox, oy = map_layers["origin_global"]
            ax.set_xlim(ox - map_radius, ox + map_radius)
            ax.set_ylim(oy - map_radius, oy + map_radius)
        else:
            ax.set_xlim(-map_radius, map_radius)
            ax.set_ylim(-map_radius, map_radius)
        return

    points = list(ego_points)
    if extra_points:
        points.extend(extra_points)
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    if not xs or not ys:
        ax.set_xlim(-10, 10)
        ax.set_ylim(-10, 10)
        return
    margin = 6.0
    ax.set_xlim(min(xs) - margin, max(xs) + margin)
    ax.set_ylim(min(ys) - margin, max(ys) + margin)


def render_static_figure(
    trace: TraceDict,
    split_idx: int,
    box_frame_idx: int,
    ego_box_frame_idx: int,
    traffic_light_frame_idx: int,
    use_global_frame: bool,
    dpi: int,
    map_radius: float,
    map_layers: Optional[Dict[str, Any]],
    map_style: str,
    show_route_nodes: bool,
    show_connector_nodes: bool,
    show_tl_hud: bool,
    fig_width: float,
    fig_height: float,
    out_png: Path,
    out_svg: Optional[Path] = None,
    manifest_meta: Optional[Dict[str, Any]] = None,
) -> None:
    frames = trace["frames"]
    n = len(frames)
    split_idx = max(0, min(split_idx, n - 1))
    box_frame_idx = max(0, min(box_frame_idx, n - 1))
    ego_box_frame_idx = max(0, min(ego_box_frame_idx, n - 1))
    traffic_light_frame_idx = max(0, min(traffic_light_frame_idx, n - 1))
    token = str(trace.get("token", "unknown"))

    ego_points, ego_speed, all_vehicles, vehicles_points = trace_to_series(trace, use_global_frame)
    nearest_dist = nearest_vehicle_distance(ego_points, vehicles_points)

    origin_global = (float(frames[0]["ego"]["x"]), float(frames[0]["ego"]["y"]))
    origin_heading = float(frames[0]["ego"]["heading"])

    fig = plt.figure(figsize=(fig_width, fig_height), dpi=dpi)
    gs = fig.add_gridspec(2, 2, height_ratios=[2.2, 1.0])
    ax_bev = fig.add_subplot(gs[0, :])
    ax_dist = fig.add_subplot(gs[1, 0])
    ax_speed = fig.add_subplot(gs[1, 1])

    draw_map_layers(
        ax_bev,
        map_layers,
        map_style=map_style,
        show_route_nodes=show_route_nodes,
        show_connector_nodes=show_connector_nodes,
    )
    draw_traffic_lights(ax_bev, trace, map_layers, traffic_light_frame_idx)
    if show_tl_hud:
        draw_traffic_light_hud(ax_bev, trace, traffic_light_frame_idx, map_layers)

    stage1 = ego_points[: split_idx + 1]
    stage2 = ego_points[split_idx:]
    if stage1:
        ax_bev.plot(
            [p[0] for p in stage1],
            [p[1] for p in stage1],
            color="#E53935",
            lw=2.0,
            zorder=14,
            label="Ego Stage1 (perturb)",
        )
    if stage2:
        ax_bev.plot(
            [p[0] for p in stage2],
            [p[1] for p in stage2],
            color="#00A86B",
            lw=2.0,
            zorder=14,
            label="Ego Stage2 (rescue)",
        )

    split_pt = ego_points[split_idx]
    ax_bev.scatter([split_pt[0]], [split_pt[1]], s=20, color="#F39C12", label="Split T+H", zorder=15)

    draw_vehicle_boxes(
        ax=ax_bev,
        vehicles=all_vehicles[box_frame_idx],
        use_global_frame=use_global_frame,
        origin_global=origin_global,
        origin_heading=origin_heading,
        label=f"Vehicles @ frame {box_frame_idx}",
    )
    draw_vehicle_boxes(
        ax=ax_bev,
        vehicles=[ego_box_payload(frames[ego_box_frame_idx])],
        use_global_frame=use_global_frame,
        origin_global=origin_global,
        origin_heading=origin_heading,
        color="#111111",
        fill_alpha=0.08,
        line_alpha=0.95,
        line_width=1.2,
        label=f"Ego box @ frame {ego_box_frame_idx}",
    )

    apply_bev_limits(ax_bev, ego_points, vehicles_points[box_frame_idx], map_layers, map_radius, use_global_frame)
    ax_bev.set_aspect("equal")
    ax_bev.grid(True, alpha=0.2)
    ax_bev.set_title(
        f"OOD Trace BEV | token={token} | frames={n} | frame={'global' if use_global_frame else 'ego-local'} "
        f"| box_frame={box_frame_idx} | tl_frame={traffic_light_frame_idx}",
        fontsize=10,
    )
    ax_bev.legend(loc="upper left", fontsize=8)

    score_line_1 = f"Stage1: {score_text(trace.get('stage1_score', {}))}"
    score_line_2 = f"Stage2: {score_text(trace.get('stage2_score', {}))}"
    diagnostic_lines = build_diagnostic_lines(trace, manifest_meta)
    diag_text = ("\n".join(diagnostic_lines) + "\n") if diagnostic_lines else ""
    ax_bev.text(
        0.01,
        0.01,
        diag_text + score_line_1 + "\n" + score_line_2,
        transform=ax_bev.transAxes,
        fontsize=7,
        va="bottom",
        ha="left",
        bbox=dict(facecolor="white", alpha=0.75, edgecolor="none", pad=2.0),
    )

    x_axis = list(range(n))
    ax_dist.plot(x_axis, nearest_dist, color="#6C63FF", lw=1.5)
    ax_dist.axvline(split_idx, color="#F39C12", lw=1.0)
    ax_dist.set_title("Nearest Vehicle Distance", fontsize=9)
    ax_dist.set_xlabel("Frame")
    ax_dist.grid(True, alpha=0.2)

    ax_speed.plot(x_axis, ego_speed, color="#039BE5", lw=1.5)
    ax_speed.axvline(split_idx, color="#F39C12", lw=1.0)
    ax_speed.set_title("Ego Speed", fontsize=9)
    ax_speed.set_xlabel("Frame")
    ax_speed.grid(True, alpha=0.2)

    fig.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_png)
    if out_svg is not None:
        fig.savefig(out_svg, format="svg")
    plt.close(fig)


def render_animation_frames(
    trace: TraceDict,
    split_idx: int,
    use_global_frame: bool,
    map_radius: float,
    map_layers: Optional[Dict[str, Any]],
    map_style: str,
    show_route_nodes: bool,
    show_connector_nodes: bool,
    show_tl_hud: bool,
) -> List[Image.Image]:
    frames = trace["frames"]
    n = len(frames)
    split_idx = max(0, min(split_idx, n - 1))
    token = str(trace.get("token", "unknown"))

    ego_points, _, all_vehicles, vehicles_points = trace_to_series(trace, use_global_frame)
    origin_global = (float(frames[0]["ego"]["x"]), float(frames[0]["ego"]["y"]))
    origin_heading = float(frames[0]["ego"]["heading"])

    images: List[Image.Image] = []
    for t in range(n):
        fig, ax = plt.subplots(1, 1, figsize=(6.5, 6.5), dpi=120)
        draw_map_layers(
            ax,
            map_layers,
            map_style=map_style,
            show_route_nodes=show_route_nodes,
            show_connector_nodes=show_connector_nodes,
        )
        draw_traffic_lights(ax, trace, map_layers, t)
        if show_tl_hud:
            draw_traffic_light_hud(ax, trace, t, map_layers)

        path = ego_points[: t + 1]
        stage1 = path[: min(t, split_idx) + 1]
        stage2 = path[max(0, split_idx): t + 1] if t >= split_idx else []
        if stage1:
            ax.plot([p[0] for p in stage1], [p[1] for p in stage1], color="#E53935", lw=2.0, zorder=14)
        if stage2:
            ax.plot([p[0] for p in stage2], [p[1] for p in stage2], color="#00A86B", lw=2.0, zorder=14)

        draw_vehicle_boxes(
            ax=ax,
            vehicles=all_vehicles[t],
            use_global_frame=use_global_frame,
            origin_global=origin_global,
            origin_heading=origin_heading,
            color="#355C7D",
            fill_alpha=0.16,
            line_alpha=0.92,
            line_width=0.9,
        )
        draw_vehicle_boxes(
            ax=ax,
            vehicles=[ego_box_payload(frames[t])],
            use_global_frame=use_global_frame,
            origin_global=origin_global,
            origin_heading=origin_heading,
            color="#111111",
            fill_alpha=0.08,
            line_alpha=0.95,
            line_width=1.1,
        )

        curr_ego = ego_points[t]
        ax.scatter([curr_ego[0]], [curr_ego[1]], s=18, color="#111111", zorder=15)

        if split_idx <= t:
            split_pt = ego_points[split_idx]
            ax.scatter([split_pt[0]], [split_pt[1]], s=16, color="#F39C12", zorder=15)

        apply_bev_limits(ax, ego_points, vehicles_points[t], map_layers, map_radius, use_global_frame)
        ax.set_aspect("equal")
        ax.grid(True, alpha=0.2)
        ax.set_title(f"{token} | t={t}/{n - 1}", fontsize=10)
        ax.set_xlabel("x")
        ax.set_ylabel("y")

        buf = io.BytesIO()
        fig.tight_layout()
        fig.savefig(buf, format="png")
        plt.close(fig)
        buf.seek(0)
        with Image.open(buf) as frame:
            images.append(frame.convert("RGB"))
        buf.close()

    return images


def render_gif(
    trace: TraceDict,
    split_idx: int,
    use_global_frame: bool,
    map_radius: float,
    map_layers: Optional[Dict[str, Any]],
    map_style: str,
    show_route_nodes: bool,
    show_connector_nodes: bool,
    show_tl_hud: bool,
    out_gif: Path,
    fps: float,
) -> None:
    images = render_animation_frames(
        trace=trace,
        split_idx=split_idx,
        use_global_frame=use_global_frame,
        map_radius=map_radius,
        map_layers=map_layers,
        map_style=map_style,
        show_route_nodes=show_route_nodes,
        show_connector_nodes=show_connector_nodes,
        show_tl_hud=show_tl_hud,
    )

    out_gif.parent.mkdir(parents=True, exist_ok=True)
    duration_ms = int(round(1000.0 / max(1, fps)))
    images[0].save(out_gif, save_all=True, append_images=images[1:], duration=duration_ms, loop=0)
    for img in images:
        img.close()


def render_mp4(
    trace: TraceDict,
    split_idx: int,
    use_global_frame: bool,
    map_radius: float,
    map_layers: Optional[Dict[str, Any]],
    map_style: str,
    show_route_nodes: bool,
    show_connector_nodes: bool,
    show_tl_hud: bool,
    out_mp4: Path,
    fps: float,
    crf: int,
    ffmpeg_bin: str,
) -> None:
    images = render_animation_frames(
        trace=trace,
        split_idx=split_idx,
        use_global_frame=use_global_frame,
        map_radius=map_radius,
        map_layers=map_layers,
        map_style=map_style,
        show_route_nodes=show_route_nodes,
        show_connector_nodes=show_connector_nodes,
        show_tl_hud=show_tl_hud,
    )
    out_mp4.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="vis_mp4_") as tmp_dir:
        tmp_path = Path(tmp_dir)
        for idx, image in enumerate(images):
            frame_path = tmp_path / f"frame_{idx:06d}.png"
            image.save(frame_path, format="PNG")

        ffmpeg_cmd = [
            ffmpeg_bin,
            "-y",
            "-framerate",
            str(max(1, fps)),
            "-i",
            str(tmp_path / "frame_%06d.png"),
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-crf",
            str(crf),
            "-movflags",
            "+faststart",
            str(out_mp4),
        ]
        result = subprocess.run(ffmpeg_cmd, capture_output=True, text=True)
        if result.returncode != 0:
            err_tail = "\n".join(result.stderr.splitlines()[-20:])
            raise RuntimeError(f"ffmpeg failed for {out_mp4}:\n{err_tail}")

    for img in images:
        img.close()


def output_path_for(input_file: Path, output_dir: Path, suffix: str) -> Path:
    stem = input_file.stem
    if stem.endswith("_vis"):
        stem = stem[:-4]
    return output_dir / f"{stem}{suffix}"


def output_path_for_stem(stem: str, output_dir: Path, suffix: str) -> Path:
    stem_clean = stem[:-4] if stem.endswith("_vis") else stem
    return output_dir / f"{stem_clean}{suffix}"


def _has_metric_cache_metadata(root: Path) -> bool:
    metadata_dir = root / "metadata"
    if not metadata_dir.exists() or not metadata_dir.is_dir():
        return False
    return any(p.suffix.lower() == ".csv" for p in metadata_dir.iterdir())


def resolve_metric_cache_root(input_path: Path) -> Path:
    p = input_path.expanduser().resolve()
    if _has_metric_cache_metadata(p):
        return p

    # Common case: user passes parent folder such as `metric_cache`, while actual root is `metric_cache/navmini`.
    if p.exists() and p.is_dir():
        children = [child for child in p.iterdir() if child.is_dir()]
        matched = [child for child in children if _has_metric_cache_metadata(child)]
        if len(matched) == 1:
            return matched[0]
        if len(matched) > 1:
            options = ", ".join(str(m) for m in matched)
            raise RuntimeError(
                f"Found multiple metric cache roots under {p}: {options}. "
                "Please pass one explicit path to --metric-cache-path."
            )

    # Also support passing deep token path; walk up to find first valid cache root.
    for parent in [p] + list(p.parents):
        if _has_metric_cache_metadata(parent):
            return parent

    raise RuntimeError(
        f"Invalid --metric-cache-path: {input_path}. "
        "Expected a directory containing 'metadata/*.csv' (e.g. metric_cache/navmini)."
    )


def _build_local_metric_cache_index(cache_root: Path) -> Dict[str, str]:
    index: Dict[str, str] = {}
    for metric_file in cache_root.rglob("metric_cache.pkl"):
        token = metric_file.parent.name
        index[token] = str(metric_file)
    return index


def build_metric_cache_loader(cache_root: Path) -> Any:
    loader = MetricCacheLoader(cache_root)
    missing_tokens = [token for token, file_path in loader.metric_cache_paths.items() if not Path(file_path).exists()]
    if not missing_tokens:
        return loader

    local_index = _build_local_metric_cache_index(cache_root)
    patched = 0
    for token in missing_tokens:
        local_path = local_index.get(token)
        if local_path is not None:
            loader.metric_cache_paths[token] = local_path
            patched += 1

    if patched > 0:
        print(
            f"[info] Metric cache metadata contained stale absolute paths; "
            f"patched {patched}/{len(missing_tokens)} token paths from local index."
        )

    return loader


def process_one_file(
    file_path: Path,
    output_dir: Path,
    split_idx_arg: Optional[int],
    box_frame: str,
    ego_box_frame: str,
    traffic_light_frame: str,
    use_global_frame: bool,
    dpi: int,
    fig_width: float,
    fig_height: float,
    save_svg: bool,
    map_radius: float,
    map_style: str,
    show_route_nodes: bool,
    show_connector_nodes: bool,
    show_tl_hud: bool,
    map_root_override: Optional[Path],
    metric_cache_loader: Optional[Any],
    map_api_cache: Dict[Tuple[str, str, str], Any],
    make_gif: bool,
    gif_fps: float,
    make_mp4: bool,
    mp4_fps: float,
    mp4_crf: int,
    ffmpeg_bin: str,
    sync_to_timestamps: bool,
    overwrite: bool,
    manifest_meta: Optional[Dict[str, Any]] = None,
    trace_override: Optional[TraceDict] = None,
    output_stem: Optional[str] = None,
) -> None:
    trace = trace_override if trace_override is not None else load_trace(file_path)
    validate_trace(trace, file_path)
    split_idx = split_idx_arg if split_idx_arg is not None else infer_split_index_from_trace(trace)
    box_frame_idx = parse_box_frame(box_frame, split_idx, int(trace["num_frames"]))
    ego_box_frame_idx = parse_box_frame(ego_box_frame, split_idx, int(trace["num_frames"]))
    traffic_light_frame_idx = parse_box_frame(traffic_light_frame, split_idx, int(trace["num_frames"]))

    map_layers = prepare_map_layers(
        metric_cache_loader=metric_cache_loader,
        map_api_cache=map_api_cache,
        trace=trace,
        use_global_frame=use_global_frame,
        map_radius=map_radius,
        map_root_override=map_root_override,
    )
    if metric_cache_loader is not None and map_layers is None:
        print(f"[warn] map not available for token={trace.get('token')} (metric cache lookup failed)")

    effective_gif_fps = float(gif_fps)
    effective_mp4_fps = float(mp4_fps)
    if sync_to_timestamps:
        realtime_fps = infer_realtime_fps_from_trace(trace)
        if realtime_fps is not None:
            effective_gif_fps = realtime_fps
            effective_mp4_fps = realtime_fps
            print(f"[info] token={trace.get('token')} realtime fps={realtime_fps:.3f}")
        else:
            print(f"[warn] token={trace.get('token')} has no valid timestamps; fallback to fixed fps.")

    stem = output_stem if output_stem is not None else file_path.stem
    out_png = output_path_for_stem(stem, output_dir, "_vis.png")
    out_svg = output_path_for_stem(stem, output_dir, "_vis.svg") if save_svg else None
    if overwrite or not out_png.exists():
        render_static_figure(
            trace=trace,
            split_idx=split_idx,
            box_frame_idx=box_frame_idx,
            ego_box_frame_idx=ego_box_frame_idx,
            traffic_light_frame_idx=traffic_light_frame_idx,
            use_global_frame=use_global_frame,
            dpi=dpi,
            map_radius=map_radius,
            map_layers=map_layers,
            map_style=map_style,
            show_route_nodes=show_route_nodes,
            show_connector_nodes=show_connector_nodes,
            show_tl_hud=show_tl_hud,
            fig_width=fig_width,
            fig_height=fig_height,
            out_png=out_png,
            out_svg=out_svg,
            manifest_meta=manifest_meta,
        )
        print(f"[saved] {out_png}")
        if out_svg is not None:
            print(f"[saved] {out_svg}")
    else:
        print(f"[skip]  exists: {out_png}")
        if out_svg is not None and (overwrite or not out_svg.exists()):
            render_static_figure(
                trace=trace,
                split_idx=split_idx,
                box_frame_idx=box_frame_idx,
                ego_box_frame_idx=ego_box_frame_idx,
                traffic_light_frame_idx=traffic_light_frame_idx,
                use_global_frame=use_global_frame,
                dpi=dpi,
                map_radius=map_radius,
                map_layers=map_layers,
                map_style=map_style,
                show_route_nodes=show_route_nodes,
                show_connector_nodes=show_connector_nodes,
                show_tl_hud=show_tl_hud,
                fig_width=fig_width,
                fig_height=fig_height,
                out_png=out_png,
                out_svg=out_svg,
                manifest_meta=manifest_meta,
            )
            print(f"[saved] {out_svg}")

    if make_gif:
        out_gif = output_path_for_stem(stem, output_dir, "_anim.gif")
        if overwrite or not out_gif.exists():
            render_gif(
                trace=trace,
                split_idx=split_idx,
                use_global_frame=use_global_frame,
                map_radius=map_radius,
                map_layers=map_layers,
                map_style=map_style,
                show_route_nodes=show_route_nodes,
                show_connector_nodes=show_connector_nodes,
                show_tl_hud=show_tl_hud,
                out_gif=out_gif,
                fps=effective_gif_fps,
            )
            print(f"[saved] {out_gif}")
        else:
            print(f"[skip]  exists: {out_gif}")

    if make_mp4:
        out_mp4 = output_path_for_stem(stem, output_dir, "_anim.mp4")
        if overwrite or not out_mp4.exists():
            render_mp4(
                trace=trace,
                split_idx=split_idx,
                use_global_frame=use_global_frame,
                map_radius=map_radius,
                map_layers=map_layers,
                map_style=map_style,
                show_route_nodes=show_route_nodes,
                show_connector_nodes=show_connector_nodes,
                show_tl_hud=show_tl_hud,
                out_mp4=out_mp4,
                fps=effective_mp4_fps,
                crf=mp4_crf,
                ffmpeg_bin=ffmpeg_bin,
            )
            print(f"[saved] {out_mp4}")
        else:
            print(f"[skip]  exists: {out_mp4}")


def main() -> None:
    args = parse_args()
    effective_history_frames = -1 if args.use_full_log else args.history_frames
    effective_future_frames = -1 if args.use_full_log else args.future_frames

    scene_pairs = collect_scene_pairs(args.scene_list_file, args.scene_list)
    manifest_meta_by_file: Dict[str, Dict[str, Any]] = {}
    input_files: List[Path] = []
    if not scene_pairs:
        if args.manifest is not None:
            input_files, manifest_meta_by_file = list_files_from_manifest(
                manifest_path=args.manifest,
                status_filter=args.status_filter,
                reason_filter=args.reason_filter,
                max_files=args.max_files,
            )
        else:
            input_files = list_input_files(args.input, args.glob, args.max_files)
        if not input_files:
            if args.manifest is not None:
                raise RuntimeError(
                    f"No files found from manifest={args.manifest} with status={args.status_filter}, "
                    f"reason={args.reason_filter}"
                )
            raise RuntimeError(f"No files found under {args.input} with pattern {args.glob}")

    if args.output_dir is not None:
        output_dir = args.output_dir
    elif scene_pairs:
        output_dir = Path("output/scene_token_visuals")
    elif args.manifest is not None:
        output_dir = args.manifest.parent
    elif args.input.is_file():
        output_dir = args.input.parent
    else:
        output_dir = args.input

    metric_cache_loader: Optional[Any] = None
    map_api_cache: Dict[Tuple[str, str, str], Any] = {}
    if args.metric_cache_path is not None:
        if not HAS_MAP_SUPPORT:
            raise RuntimeError(f"Map support imports failed: {MAP_IMPORT_ERROR}")
        if args.map_root_override is not None and not args.map_root_override.exists():
            raise RuntimeError(f"--map-root-override does not exist: {args.map_root_override}")
        cache_root = resolve_metric_cache_root(args.metric_cache_path)
        metric_cache_loader = build_metric_cache_loader(cache_root)
        print(f"Map overlay enabled from metric cache: {cache_root}")
        if args.map_root_override is not None:
            print(f"Using map root override: {args.map_root_override.resolve()}")

    if scene_pairs:
        mini_log_root = args.mini_log_root.expanduser().resolve()
        if not mini_log_root.exists():
            raise FileNotFoundError(f"--mini-log-root does not exist: {mini_log_root}")
        print(f"Found {len(scene_pairs)} scene pair(s). Writing to: {output_dir.resolve()}")

        log_cache: Dict[str, List[Dict[str, Any]]] = {}
        num_ok = 0
        for log_name, token in scene_pairs:
            if log_name not in log_cache:
                log_file = mini_log_root / f"{log_name}.pkl"
                if not log_file.exists():
                    print(f"[warn] missing log file: {log_file}")
                    log_cache[log_name] = []
                else:
                    with log_file.open("rb") as f:
                        log_cache[log_name] = pickle.load(f)
            trace = build_trace_from_scene_pair(
                log_frames=log_cache[log_name],
                log_name=log_name,
                token=token,
                history_frames=effective_history_frames,
                future_frames=effective_future_frames,
            )
            if trace is None:
                print(f"[warn] token not found in log: {log_name} / {token}")
                continue

            stem = f"{log_name}__{token}"
            process_one_file(
                file_path=Path(f"{stem}.json"),
                output_dir=output_dir,
                split_idx_arg=args.split_index,
                box_frame=args.box_frame,
                ego_box_frame=args.ego_box_frame,
                traffic_light_frame=args.traffic_light_frame,
                use_global_frame=args.global_frame,
                dpi=args.dpi,
                fig_width=args.fig_width,
                fig_height=args.fig_height,
                save_svg=args.save_svg,
                map_radius=args.map_radius,
                map_style=args.map_style,
                show_route_nodes=(not args.hide_route_nodes),
                show_connector_nodes=(not args.hide_connector_nodes),
                show_tl_hud=args.show_tl_hud,
                map_root_override=args.map_root_override,
                metric_cache_loader=metric_cache_loader,
                map_api_cache=map_api_cache,
                make_gif=args.make_gif,
                gif_fps=args.gif_fps,
                make_mp4=args.make_mp4,
                mp4_fps=args.mp4_fps,
                mp4_crf=args.mp4_crf,
                ffmpeg_bin=args.ffmpeg_bin,
                sync_to_timestamps=args.sync_to_timestamps,
                overwrite=args.overwrite,
                manifest_meta={"result_status": "scene_pair", "log_name": log_name},
                trace_override=trace,
                output_stem=stem,
            )
            num_ok += 1
        print(f"[done] rendered {num_ok}/{len(scene_pairs)} scene pair(s).")
        return

    print(f"Found {len(input_files)} file(s). Writing to: {output_dir.resolve()}")
    for file_path in input_files:
        process_one_file(
            file_path=file_path,
            output_dir=output_dir,
            split_idx_arg=args.split_index,
            box_frame=args.box_frame,
            ego_box_frame=args.ego_box_frame,
            traffic_light_frame=args.traffic_light_frame,
            use_global_frame=args.global_frame,
            dpi=args.dpi,
            fig_width=args.fig_width,
            fig_height=args.fig_height,
            save_svg=args.save_svg,
            map_radius=args.map_radius,
            map_style=args.map_style,
            show_route_nodes=(not args.hide_route_nodes),
            show_connector_nodes=(not args.hide_connector_nodes),
            show_tl_hud=args.show_tl_hud,
            map_root_override=args.map_root_override,
            metric_cache_loader=metric_cache_loader,
            map_api_cache=map_api_cache,
            make_gif=args.make_gif,
            gif_fps=args.gif_fps,
            make_mp4=args.make_mp4,
            mp4_fps=args.mp4_fps,
            mp4_crf=args.mp4_crf,
            ffmpeg_bin=args.ffmpeg_bin,
            sync_to_timestamps=args.sync_to_timestamps,
            overwrite=args.overwrite,
            manifest_meta=manifest_meta_by_file.get(str(file_path.resolve())),
        )


if __name__ == "__main__":
    main()
